export default {
  FONT_SIZE_SMALL: 14,
  FONT_SIZE_MEDIUM: 16,
  FONT_SIZE_LARGE: 18,
  FONT_SIZE_HEADERBAR: 20,

  FONT_WEIGHT_LIGHT: '200',
  FONT_WEIGHT_MEDIUM: '600',
  FONT_WEIGHT_BOLD: '700',



  // DARK_FONT: '#000',
  // LIGHT_FONT: '#fff',

  // PRIMARY_FONT_FAMILY: 'AvenirNextCondensed-Regular',
  PRIMARY_FONT_FAMILY: 'RobotoCondensed-Regular',
  // PRIMARY_FONT_FAMILY: 'System',
  SECONDARY_FONT_FAMILY: 'Eczar-Regular',
  //SECONDARY_FONT_FAMILY: 'System',



  //colors
  PRIMARY_BACKGROUND: "#32333D",
  SECONDARY_BACKGROUND: '#47474D',

  PRIMARY_COLOR: '#364590',

  HEADER_BACKGROUND: '#47474D',
  LIST_SUBHEADING_COLOR: '#FFCF44',
  PRIMARY_BUTTON_BACKGROUND: '#364590',
  EDIT_ICON_COLOR: '#FFCF44',
  PROGRESS_COLOR: '#FF6859',
  COMPLETED_COLOR: '#1EB980',

  PRIMARY_FONT_COLOR: '#FFF',

  PLACEHOLDER_FONT_COLOR: '#A1A1A1',
  HELPER_FONT_COLOR: '#A1A1A1',

  BORDER_COLOR: '#fff',
  BORDER_BOTTOM_WIDTH: 2,



  DISABLED_TEXT_COLOR: '#a7a8a8',
  ERROR_RED: '#ff190c',

  ACTIVE_TAB_COLOR: '#72DEFF',
  ACTIVE_TAB_WIDTH: 3,

  ACCENT_RED: '#E25142',
  ACCENT_ORANGE: '#FF6859',
  ACCENT_YELLOW: '#FFCF44',
  ACCENT_PURPLE: '#B15DFF',
  ACCENT_BLUE: '#72DEFF',
  ACCENT_GREEN: '#1EB980',
}
