
export const FILTER_BODY_MEASUREMENTS = 'FILTER_BODY_MEASUREMENTS';
export const FILTER_EXERCISES = 'FILTER_EXERCISES';
export const SELECTED_SCOPE = 'SELECTED_SCOPE';
export const GET_AVAILABLE_EXERCISES =  'GET_AVAILABLE_EXERCISES';
export const CALCULATE_DATE_RANGES = 'CALCULATE_DATE_RANGES';

