

export const LISTEN_FOR_BODY_LOGS = 'LISTEN_FOR_BODY_LOGS';
export const RECIEVED_BODY_LOGS = 'RECIEVED_BODY_LOGS';
export const LISTEN_FOR_BODY_LOGS_ERROR = 'LISTEN_FOR_BODY_LOGS_ERROR';

export const CHART_FORMATS = {
  LINE_CHART: 'LINE_CHART',
};
