
export const SELECT_MUSCLE_GROUP = 'SELECT_MUSCLE_GROUP';
export const SELECT_EXERCISE = 'SELECT_EXERCISE';
export const REMOVE_SELECTED_EXERICISE = 'REMOVE_SELECTED_EXERCISE';
export const UPDATE_EXERCISE_LIST = 'UPDATE_EXERCISE_LIST';

export const OPEN_EXERCISE_LIST = 'OPEN_EXERCISE_LIST';
export const ADD_EXERCISES = 'ADD_EXERCISES';
export const RESET_DATA = 'RESET_DATA';
export const UPDATE_FIELD = 'UPDATE_FIELD';
export const SORT_EXERCISES = 'SORT_EXERCISES';
export const SAVE_EXERCISE_ORDER = 'SAVE_EXERCISE_ORDER';
export const OPEN_DELETE_PAGE = 'OPEN_DELETE_PAGE';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';
export const OPEN_CUSTOM_SET = 'OPEN_CUSTOM_SET';
export const SAVE_CUSTOM_SET = 'SAVE_CUSTOM_SET';

export const ADD_CUSTOM_EXERCISE = 'ADD_CUSTOM_EXERCISE';
export const SAVE_EXERCISE_TO_PROFILE = 'SAVE_EXERCISE_TO_PROFILE';

export const SAVE_WORKOUT = 'SAVE_WORKOUT';
export const SAVE_PROGRAM = 'SAVE_PROGRAM';
export const SAVE_SUCCESSFUL = 'SAVE_SUCCESSFUL';
export const SAVE_FAILED = 'SAVE_FAILED';
export const HIDE_ALERT = 'HIDE_ALERT';

