
export const ADD_PROGRAM = 'ADD_PROGRAM';

export const ADD_WORKOUT = 'ADD_WORKOUT';

export const BUILD_EDIT_FIELD = 'BUILD_EDIT_FIELD';

export const BUILD_EDIT_PROGRAM = 'BUILD_EDIT_PROGRAM';

export const BUILD_EDIT_WORKOUT = 'BUILD_EDIT_WORKOUT';

export const BUILD_DELETE_EXERCISE = 'BUILD_DELETE_EXERCISE';

export const BUILD_CHANGE_WEEK = 'BUILD_CHANGE_WEEK';

export const BUILD_SAVE_WORKOUT = 'BUILD_SAVE_WORKOUT';

export const COPY_BUILD_OBJECT = 'COPY_BUILD_OBJECT';

export const CREATE_BUILD_OBJECT = 'CREATE_BUILD_OBJECT';

export const OPEN_DELETE_SCREEN = 'OPEN_DELETE_SCREEN';

export const STORE_BUILD_OBJECT_CONFIG = 'STORE_BUILD_OBJECT_CONFIG';

export const UPDATE_DAY_TITLE = 'UPDATE_DAY_TITLE';
