
export const LISTEN_FOR_EXERCISE_LIST = 'LISTEN_FOR_EXERCISE_LIST';
export const RECEIVED_EXERCISE_LIST = 'RECEIVED_EXERCISE_LIST';
export const RECEIVED_CUSTOM_EXERCISES = 'RECEIVED_CUSTOM_EXERCISES';
