
export const ADD_CUSTOM_EXERCISE_REQUEST = 'ADD_CUSTOM_EXERCISE_REQUEST';

export const ADD_CUSTOM_EXERCISE_SUCCESS = 'ADD_CUSTOM_EXERCISE_SUCCESS';

export const ADD_CUSTOM_EXERCISE_FAILURE = 'ADD_CUSTOM_EXERCISE_SUCCESS';

export const BUILDING_ADD_EXERCISES = 'BUILDING_ADD_EXERCISES';

export const SELECT_MUSCLE_GROUP = 'SELECT_MUSCLE_GROUP';

export const SELECT_EXERCISE = 'SELECT_EXERCISE';

export const SETUP_EXERCISE_LIST = 'SETUP_EXERCISE_LIST';

export const OPEN_CUSTOM_SET = 'OPEN_CUSTOM_SET';

export const SAVE_CUSTOM_SET = 'SAVE_CUSTOM_SET';

export const BUILD_UPDATE_EXERCISE_ORDER = 'BUILD_UPDATE_EXERCISE_ORDER';
