

export const ADD_CUSTOM_EXERCISE = 'ADD_CUSTOM_EXERCISE';

export const ADD_EXERCISES = 'ADD_EXERCISES';

export const GET_EXERCISES_REQUEST = 'GET_EXERCISES_REQUEST';
export const GET_EXERCISES_SUCCESS = 'GET_EXERCISES_SUCCESS';
export const GET_EXERCISES_FAILURE = 'GET_EXERCISES_FAILURE';


export const OPEN_EXERCISE_LIST = 'OPEN_EXERCISE_LIST';

export const SELECT_MUSCLE_GROUP = 'SELECT_MUSCLE_GROUP';

export const STORE_EXERCISE_LIST = 'STORE_EXERCISE_LIST';

export const UPDATE_SELECTIONS = 'UPDATE_SELECTIONS';

export const UPDATE_PROFILE_EXERCISES_REQUEST = 'UPDATE_PROFILE_EXERCISES_REQUEST';

export const UPDATE_PROFILE_EXERCISES_SUCCESS = 'UPDATE_PROFILE_EXERCISES_SUCCESS';

export const UPDATE_PROFILE_EXERCISES_FAILED = 'UPDATE_PROFILE_EXERCISES_FAILED';
