
export const LOG_SELECTED_DAY = 'LOG_SELECTED_DAY';

export const LOG_UPDATE_WORKOUT = 'LOG_UPDATE_WORKOUT';

export const LOG_UPDATE_BODY_LOG = 'LOG_UPDATE_BODY_LOG';

export const UPDATE_LOGS_REQUEST = 'UPDATE_LOGS_REQUEST';

export const SAVE_LOG_UPDATE = 'SAVE_LOG_UPDATE';
