

export const MARK_DATES = 'MARK_DATES';

export const SELECTED_CALENDAR_DAY = 'SELECTED_CALENDAR_DAY';

export const UPDATE_WORKOUT_LOG = 'UPDATE_WORKOUT_LOG';

export const UPDATE_BODY_LOG = 'UPDATE_BODY_LOG';
