export const UPDATED_PROFILE = 'UPDATED_PROFILE';
export const EMAIL_UPDATED = 'EMAIL_UPDATED';
export const UPDATED_MEASUREMENTS = 'UPDATED_MEASUREMENTS';
export const UPDATE_LOADING = 'UPDATE_LOADING';


export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED';
