export const UPDATED_PROFILE = 'UPDATED_PROFILE';
export const EMAIL_UPDATED = 'EMAIL_UPDATED';
export const UPDATED_MEASUREMENTS = 'UPDATED_MEASUREMENTS';
export const UPDATE_LOADING = 'UPDATE_LOADING';



/* v2 */

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED';

export const UPDATE_FIELD_REQUEST = 'UPDATE_FIELD_REQUEST';
export const UPDATE_FIELD_SUCCESS = 'UPDATE_FIELD_SUCCESS';
export const UPDATE_FIELD_FAILED = 'UPDATE_FIELD_FAILED';
