

export const ADD_PROGRAM = 'ADD_PROGRAM';

export const EDIT_FIELD = 'EDIT_FIELD';

export const EDIT_PROGRAM = 'EDIT_PROGRAM';

export const CREATE_PROGRAM_OBJECT = 'CREATE_PROGRAM_OBJECT';

export const PROGRAM_UPDATE_DAY = 'PROGRAM_UPDATE_DAY';

export const PROGRAM_CHANGE_WEEK = 'PROGRAM_CHANGE_WEEK';

export const PROGRAM_ADD_EXERCISE = 'PROGRAM_ADD_EXERCISE';

export const PROGRAM_COPY_WEEK = 'PROGRAM_COPY_WEEK';

export const PROGRAM_DELETE_EXERCISE = 'PROGRAM_DELETE_EXERCISE';

export const PROGRAM_OPEN_CUSTOM_SET = 'PROGRAM_OPEN_CUSTOM_SET';

export const PROGRAM_SAVE_ORDER = 'PROGRAM_SAVE_ORDER';

export const PROGRAM_SAVE_CUSTOM_SET = 'PROGRAM_SAVE_CUSTOM_SET';

export const SORT_EXERCISES = 'SORT_EXERCISES';

export const STORE_PROGRAM_CONFIG = 'STORE_PROGRAM_CONFIG';

export const PROGRAM_OPEN_DELETE = 'PROGRAM_OPEN_DELETE';

