export const ADD_EXERCISES = 'ADD_EXERCISES';

export const BUILD_EXERCISE_HISTORY = 'BUILD_EXERCISE_HISTORY';

export const CALCULATE_PROGRAM_ATTEMPT = 'CALCULATE_PROGRAM_ATTEMPT';

export const FORMAT_EXERCISES = 'FORMAT_EXERCISES';

export const MARK_PROGRAM_COMPLETED_FLAGS = 'MARK_PROGRAM_COMPLETED_FLAGS';

export const QUICK_TRACK = 'QUICK_TRACK';

export const REMOVE_EXERCISE = 'REMOVE_EXERCISE';

export const SAVE_TRACKED_WORKOUT_REQUEST = 'SAVE_TRACKED_WORKOUT_REQUEST';

export const SAVE_TRACKED_WORKOUT_SUCCESS = 'SAVE_TRACKED_WORKOUT_SUCCESS';

export const SELECTED_WORKOUT = 'SELECTED_WORKOUT';

export const SELECTED_PROGRAM = 'SELECTED_PROGRAM';

export const SELECTED_DAY = 'SELECTED_DAY';

export const SELECTED_WEEK = 'SELECTED_WEEK';

export const STORE_ADD_EXERCISE_INDEX = 'STORE_ADD_EXERCISE_INDEX';

export const UPDATE_FIELD = 'UPDATE_FIELD';

// V2 CONSTANTS
export const TRACK_ADD_EXERCISES = 'TRACK_ADD_EXERCISES';
export const TRACK_ADD_EXERCISE_INDEX = 'TRACK_ADD_EXERCISE_INDEX';
export const TRACK_EDIT_FIELD = 'TRACK_EDIT_FIELD';
export const TRACK_REMOVE_EXERCISE = 'TRACK_REMOVE_EXERCISE';
export const TRACK_SAVE_EXERCISES = 'TRACK_SAVE_EXERCISES';
export const TRACK_SELECTED_PROGRAM = 'TRACK_SELECTED_PROGRAM';
export const TRACK_SELECTED_WORKOUT = 'TRACK_SELECTED_WORKOUT';
export const TRACK_SELECTED_PROGRAM_DAY = 'TRACK_SELECTED_PROGRAM_DAY';

export const MODIFY_SETS = 'MODIFY_SETS';
