export const ADD_EXERCISES = 'ADD_EXERCISES';

export const BUILD_EXERCISE_HISTORY = 'BUILD_EXERCISE_HISTORY';

export const CALCULATE_PROGRAM_ATTEMPT = 'CALCULATE_PROGRAM_ATTEMPT';

export const CALCULATE_PROGRAM_PERCENTAGES = 'CALCULATE_PROGRAM_PERCENTAGES';

export const CONTINUE_PROGRAM = 'CONTINUE_PROGRAM';

export const FORMAT_EXERCISES = 'FORMAT_EXERCISES';

// TODO this is now in workout api
export const GET_TRACKED_WORKOUTS_REQUEST = 'GET_TRACKED_WORKOUTS_REQUEST';

// TODO this is now in workout api
export const GET_TRACKED_WORKOUTS_SUCCESS = 'GET_TRACKED_WORKOUTS_SUCCESS';

// TODO this is now in workout api
export const GET_TRACKED_WORKOUTS_FAILED = 'GET_TRACKED_WORKOUTS_FAILED';

export const MARK_PROGRAM_COMPLETED_FLAGS = 'MARK_PROGRAM_COMPLETED_FLAGS';

export const MODIFY_SETS = 'MODIFY_SETS';

export const QUICK_TRACK = 'QUICK_TRACK';

export const REMOVE_EXERCISE = 'REMOVE_EXERCISE';

export const RESET_PROGRAM = 'RESET_PROGRAM';

export const SAVE_TRACKED_WORKOUT_REQUEST = 'SAVE_TRACKED_WORKOUT_REQUEST';

export const SAVE_TRACKED_WORKOUT_SUCCESS = 'SAVE_TRACKED_WORKOUT_SUCCESS';

export const SAVE_TRACKED_WORKOUT_FAILED = 'SAVE_TRACKED_WORKOUT_FAILED';

export const SELECTED_WORKOUT = 'SELECTED_WORKOUT';

export const SELECTED_PROGRAM = 'SELECTED_PROGRAM';

export const SELECTED_DAY = 'SELECTED_DAY';

export const SELECTED_WEEK = 'SELECTED_WEEK';

export const STORE_ADD_EXERCISE_INDEX = 'STORE_ADD_EXERCISE_INDEX';

export const UPDATE_FIELD = 'UPDATE_FIELD';

export const UPDATED_PROGRAM_ATTEMPTS = 'UPDATED_PROGRAM_ATTEMPTS';


// V2 CONSTANTS

export const TRACK_SELECTED_PROGRAM = 'TRACK_SELECTED_PROGRAM';
export const TRACK_SELECTED_WORKOUT = 'TRACK_SELECTED_WORKOUT';
