
export const ADD_WORKOUT = 'ADD_WORKOUT';

export const CREATE_WORKOUT_OBJECT = 'CREATE_WORKOUT_OBJECT';

export const EDIT_WORKOUT = 'EDIT_WORKOUT';

export const STORE_WORKOUT_CONFIG = 'STORE_WORKOUT_CONFIG';

export const WORKOUT_DELETE_EXERCISE = 'WORKOUT_DELETE_EXERCISE';

export const WORKOUT_OPEN_CUSTOM_SET = 'WORKOUT_OPEN_CUSTOM_SET';

export const WORKOUT_UPDATE_DAY = 'WORKOUT_UPDATE_DAY';

export const WORKOUT_SAVE_ORDER = 'WORKOUT_SAVE_ORDER';

export const WORKOUT_SAVE_CUSTOM_SET = 'WORKOUT_SAVE_CUSTOM_SET';

export const EDIT_FIELD = 'EDIT_FIELD';