
// On login && anytime these collection are updated

export const FETCH_COMPLETED_EXERCISES_REQUEST = 'FETCH_COMPLETED_EXERCISES_REQUEST';
export const FETCH_COMPLETED_EXERCISES_SUCCESS = 'FETCH_COMPLETED_EXERCISES_SUCCESS';
export const FETCH_COMPLETED_EXERCISES_FAILED = 'FETCH_COMPLETED_EXERCISES_FAILED';


export const FETCH_SAVED_WORKOUTS_REQUEST = 'FETCH_SAVED_WORKOUTS_REQUEST';
export const FETCH_SAVED_WORKOUTS_SUCCESS = 'FETCH_SAVED_WORKOUTS_SUCCESS';
export const FETCH_SAVED_WORKOUTS_FAILED = 'FETCH_SAVED_WORKOUTS_FAILED';


// Track stack
export const SAVE_TRACKED_WORKOUT_REQUEST = 'SAVED_TRACKED_WORKOUT_REQUEST';
export const SAVE_TRACKED_WORKOUT_SUCCESS = 'SAVED_TRACKED_WORKOUT_SUCCESS';
export const SAVE_TRACKED_WORKOUT_FAILED = 'SAVED_TRACKED_WORKOUT_FAILED';


// Build stack
export const SAVE_WORKOUT_REQUEST = 'SAVE_WORKOUT_REQUEST';
export const SAVE_WORKOUT_SUCCESS = 'SAVE_WORKOUT_SUCCESS';
export const SAVE_WORKOUT_FAILED = 'SAVE_WORKOUT_FAILED';

export const BUILD_SAVE_REDIRECT_DONE = 'BUILD_SAVE_REDIRECT_DONE';



// Logs stack
export const SAVE_WORKOUT_LOG_REQUEST =  'SAVE_WORKOUT_LOG_REQUEST';
export const SAVE_WORKOUT_LOG_SUCCESS = 'SAVE_WORKOUT_LOG_SUCCESS';
export const SAVE_WORKOUT_LOG_FAILED = 'SAVE_WORKOUT_LOG_FAILED';

export const SAVE_BODY_LOG_REQUEST = 'SAVE_BODY_LOG_REQUEST';
export const SAVE_BODY_LOG_SUCCESS = 'SAVE_BODY_LOG_SUCCESS';
export const SAVE_BODY_LOG_FAILED = 'SAVE_BODY_LOG_FAILED';

export const GET_BODY_LOGS_REQUEST = 'GET_BODY_LOGS_REQUEST';
export const GET_BODY_LOGS_SUCCESS = 'GET_BODY_LOGS_SUCCESS';
export const GET_BODY_LOGS_FAILED = 'GET_BODY_LOGS_FAILED';

